const fs = require('fs');
const path = require('path');

// Path for the generated config file inside the 'js' directory
const configPath = path.join(__dirname, 'js', 'config.generated.js');

// Vercel automatically exposes env vars with this prefix to the frontend build.
// We will create a config file from them.
const firebaseConfig = {
  apiKey: process.env.PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.PUBLIC_FIREBASE_APP_ID,
  measurementId: process.env.PUBLIC_FIREBASE_MEASUREMENT_ID,
};

const tomorrowApiKey = process.env.PUBLIC_TOMORROW_IO_API_KEY;
const grokApiKey = process.env.PUBLIC_GROK_API_KEY;
const groqApiKey = process.env.PUBLIC_GROQ_API_KEY;

// Check if all required Firebase keys are present
const firebaseKeys = Object.values(firebaseConfig);
const allFirebaseKeysPresent = firebaseKeys.every(key => key && key.length > 0);

if (!allFirebaseKeysPresent) {
  console.error('Missing one or more Firebase environment variables. Please check your Vercel project settings.');
  // Exit with an error code to fail the build
  process.exit(1);
}

// Create the content for the config file
const fileContent = `
// This file is auto-generated by Vercel during the build process.
// Do not edit this file directly.

(function () {
  console.log('✅ Loading configuration from Vercel environment.');

  window.FIREBASE_CONFIG = {
    apiKey: "${firebaseConfig.apiKey}",
    authDomain: "${firebaseConfig.authDomain}",
    projectId: "${firebaseConfig.projectId}",
    storageBucket: "${firebaseConfig.storageBucket}",
    messagingSenderId: "${firebaseConfig.messagingSenderId}",
    appId: "${firebaseConfig.appId}",
    measurementId: "${firebaseConfig.measurementId}"
  };

  window.TOMORROW_IO_API_KEY = "${tomorrowApiKey || ''}";
  window.GROK_API_KEY = "${grokApiKey || ''}";
  window.GROQ_API_KEY = "${groqApiKey || ''}";
})();
`;

// Write the file
try {
  fs.writeFileSync(configPath, fileContent.trim());
  console.log(`✅ Successfully created config file at ${configPath}`);
} catch (error) {
  console.error(`❌ Error writing config file: ${error.message}`);
  process.exit(1);
}
